# ansible-playbook --ask-become-pass init.yml --verbose
---
- name: Bootstrap development environment
  hosts: localhost
  become: false  
  vars:
    common_packages:
      - git 
      - tmux 
      - make 
      - cmake 
      - node 
      - npm       
      - curl
      - wget
      - htop
      - unzip
      - zip
      - go
      - zig
      - ripgrep
      - python3       
      - virtualenv    
      - docker        
      - docker-compose 
      - neovim        
      - fzf
      - zsh
      - lazygit
      - jq
      - nginx
      - terraform
      - openssl
      - kubectl 
  tasks:
    - name: Install packages with apt on Ubuntu
      ansible.builtin.apt:
        name: "{{ common_packagesq }}"
        state: present
      when: ansible_distribution == "Ubuntu"
      register: package_result
    - name: Install common packages with brew on MacOS
      ansible.builtin.homebrew:
        name: "{{ common_packages }}"
        state: present
      when: ansible_distribution == "MacOSX"
      register: package_result
    - name: Display package installation results
      debug:
        msg: |
          Package installation result:
          {{ package_result }}
      when: package_result is defined